project_id = "yxcunbkdjblredimerwk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://yxcunbkdjblredimerwk.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[edge_functions]
enabled = true
port = 54323
import_map = "./functions/_shared/import_map.json"

[functions]
[functions.mark-analyzed]
verify_jwt = false

[functions.sample-status]
verify_jwt = false

[functions.submit-sample]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.update-sample-status]
verify_jwt = false